[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"
  included_files = [
    "netlify/functions/**",
    "node_modules/@napi-rs/canvas/**"
  ]

[[redirects]]
  from = "/card"
  to = "/.netlify/functions/card"
  status = 200

[[redirects]]
  from = "/card/*"
  to = "/.netlify/functions/card/:splat"
  status = 200
